# -*- coding: utf-8 -*-
# @Author: Yanqi Gu
# @Date:   2019-03-18 16:21:49
# @Last Modified by:   Yanqi Gu
# @Last Modified time: 2019-03-22 10:55:15

def BKDR(msg, seed):
	# This is an implementation of BKDR Hash.
	# The algorithm is invented by Brian Kernighan, Dennis Ritchie.
	# Hash generated by this algorithm) is 32 bits (4 Bytes) in length
	# Input: Seed can be any combination of 31, for example,31 131 1313 13131 131313
	# Reference: http://www.partow.net/programming/hashfunctions/
	hash = 0
	for i in range(len(msg)):
		hash = (hash * seed) + ord(msg[i])
	return hash 

def main():
    msg = "I love you"
	seed = 31
	print(BKDR(msg, seed))

if __name__ == '__main__':
	main()
